services:
  file-validation-nextjs-nginx:
    build:
      context: .
      target: development
    container_name: file-validation-nextjs-nginx
    environment:
      NODE_ENV: development
      DOCKER_ENV: "true"
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync 
          path: ./app
          target: /file-validation-nextjs-nginx/app
        - action: sync
          path: ./next.config.ts
          target: /file-validation-nextjs-nginx/next.config.ts
        - action: rebuild
          path: ./package.json
        - action: sync
          path: ./public
          target: /file-validation-nextjs-nginx/public
  nginx:
    build:
      context: ./nginx
    develop:
      watch:
        - action: sync+restart
          path: ./default.conf
          target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - file-validation-nextjs-nginx